### ISSUE TITLE
Docker for mysql

### ISSUE THREAD

**Issue by vunguyen1989** [vunguyen1989/TestMaster#2]
- we'll use MySQL for our database
- we need to create a docker-compose file for this

**Comment by QuangNgThanh** [comment]
version: '3'

services:

  mysql-development:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysqldb
    ports:
      - "3308:3306"

**Comment by vunguyen1989** [comment]
you should create a pull request(PR) first, then we will review on your PR.

not just only showing something working, please make it completed.
